#1 노름 계산하는 방법 : $D(x, x^{*})$ 
---

$L_{p} = (\sum^{n}_{i} |x_i - x^{*}_i|^{p})^{1/p}$

계산식으로 $L_1$, $L_2$, $L_{\infty}$가 있다.

이 계산식은 원본 샘플과 적대적 샘플의 차이인 왜곡을 측정할 때, 사용이 된다.

3가지 중에 어떤 방식이 가장 좋은 측정도구는 상황에 따라 다르지만, 공통적으로 $L_{p}$값이 작아지면 작아질수록 원본 샘플과 적대적 샘플의 유사성이 증가가 된다.
따라서, $L_{p}$ 수치가 작아지면 사람의 눈에 볼 때에도 그 차이가 작기 때문에 적대적 샘플 시 중요한 판단요소가 된다.


(1) $L_{1}$ 에 대한 실습

In [14]:
import numpy as np
x_org = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   
x_adv = np.array([[1.1, 2.1, 3.2], [4.1, 5.1, 6.1], [7.3, 7.9, 8.9]])
print(x_org)
print(x_org.shape)
print(x_adv)
print(x_adv.shape)

abs = np.abs(x_org-x_adv)
sum = np.sum(abs)
print(abs)
print(sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1.1 2.1 3.2]
 [4.1 5.1 6.1]
 [7.3 7.9 8.9]]
(3, 3)
[[0.1 0.1 0.2]
 [0.1 0.1 0.1]
 [0.3 0.1 0.1]]
1.1999999999999984


(2) $L_{2}$ 에 대한 실습

In [17]:
import numpy as np
x_org = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   
x_adv = np.array([[1.1, 2.1, 3.2], [4.1, 5.1, 6.1], [7.3, 7.9, 8.9]])
print(x_org)
print(x_org.shape)
print(x_adv)
print(x_adv.shape)

abs = np.abs((x_org-x_adv)**2)
sum = np.sum(abs)
squre = np.square(sum)
print(abs)
print(sum)
print(squre)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1.1 2.1 3.2]
 [4.1 5.1 6.1]
 [7.3 7.9 8.9]]
(3, 3)
[[0.01 0.01 0.04]
 [0.01 0.01 0.01]
 [0.09 0.01 0.01]]
0.19999999999999965
0.03999999999999986


(3) $L_{∞}$ 에 대한 실습

In [21]:
import numpy as np
x_org = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   
x_adv = np.array([[1.1, 2.1, 3.2], [4.1, 5.1, 6.1], [7.3, 7.9, 8.9]])
print(x_org)
print(x_org.shape)
print(x_adv)
print(x_adv.shape)

abs = np.abs((x_org-x_adv))
max = np.max(abs)
print(abs)
print(max)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1.1 2.1 3.2]
 [4.1 5.1 6.1]
 [7.3 7.9 8.9]]
(3, 3)
[[0.1 0.1 0.2]
 [0.1 0.1 0.1]
 [0.3 0.1 0.1]]
0.2999999999999998
